version: "2"
services:
  devel:
    build: .
    restart: always
    command: run-devel
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
  tests:
    build: .
    command: launch-tests
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=main.test_settings
