## action.yml
name: 'Tests'
on:
  push:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
#        python: [ 3.6, 3.7, 3.8 ]
        python: [ 3.6 ]
        django: [
#            "Django>=1.11,<2.0",
#            "Django>=2.0,<2.1",
#            "Django>=2.1,<2.2",
#            "Django>=2.2,<3.0",
            "Django>=3.0,<4.0"
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install pipenv and django
        run: |
          pip install pipenv
          pipenv lock --dev -r > requirements.txt
          pip install "${{ matrix.django }}"
      - name: Run tests
        run: |
          cd src
          pytest -v
