## action.yml
name: 'Tests'
on:
  push:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [ 3.6 ]
        django: [
          "Django>=3.0,<4.0"
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install pipenv and dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: |
            lock --dev -r > requirements.txt
        run: |
            pip install -r requirements.txt
            pip pip install "${{ matrix.django }}"
      - name: Run tests
        run: |
          coverage run
          coverage report -m
